apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ad-mnist
spec:
  template:
    spec:
      containers:
      - image: seldonio/mnistad:0.0.1
        args:
        - --model_name
        - mnistad
        - --storage_uri
        - ./ad_vae_mnist/
        - --reply_url
        - http://message-dumper.default
